# git init
# git remote add origin https://github.com/contactlab/contactlab-magento-connect.git
# git pull origin develop
# git checkout feature/travis-test
language: php
php:
  - 5.5
test:
  adapter: mysql
  database: myapp_test
  username: travis
  encoding: utf8
before_script:
  - curl -s http://getcomposer.org/installer | php
  - wget http://www.webformat.com/4GMVhgIhcUaHIz9s/composer.json
  - php composer.phar install
  - wget https://raw.githubusercontent.com/colinmollenhour/modman/master/modman
  - chmod +x modman
  - ./modman init
  - ./modman clone git://github.com/EcomDev/EcomDev_PHPUnit.git
  - mysql -e 'create database contactlab;'
script: phpunit tests
