# git init
# git remote add origin https://github.com/contactlab/contactlab-magento-connect.git
# git pull origin develop
# git checkout feature/travis-test
language: php
php:
  - 5.5
test:
  adapter: mysql
  database: myapp_test
  username: travis
  encoding: utf8
before_script:
  - curl -s http://getcomposer.org/installer | php
  - wget http://www.webformat.com/4GMVhgIhcUaHIz9s/composer.json
  - php composer.phar install
  - wget https://raw.githubusercontent.com/colinmollenhour/modman/master/modman
  - chmod +x modman
  - ./modman init
  - ./modman clone git://github.com/EcomDev/EcomDev_PHPUnit.git

  - mv app/etc/local.xml.template app/etc/local.xml
  - sed -i -re 's/\{\{admin_frontname\}\}/admin/g' app/etc/local.xml
  - sed -i -re 's/\{\{session_save\}\}/files/g' app/etc/local.xml
  - sed -i -re 's/\{\{session_save\}\}/files/g' app/etc/local.xml
  - sed -i -re 's/\{\{db_pdo_type\}\}//g' app/etc/local.xml
  - sed -i -re 's/\{\{db_type\}\}/pdo_mysql/g' app/etc/local.xml
  - sed -i -re 's/\{\{db_model\}\}/mysql4/g' app/etc/local.xml
  - sed -i -re 's/\{\{db_init_statemants\}\}/SET NAMES utf8/g' app/etc/local.xml
  - sed -i -re 's/\{\{db_name\}\}/contactlab_db/g' app/etc/local.xml
  - sed -i -re 's/\{\{db_pass\}\}//g' app/etc/local.xml
  - sed -i -re 's/\{\{db_user\}\}/travis/g' app/etc/local.xml
  - sed -i -re 's/\{\{db_host\}\}/localhost/g' app/etc/local.xml
  - sed -i -re 's/\{\{date\}\}/Wed, 28 Aug 2013 09:51:02 +0000/g' app/etc/local.xml
  - sed -i -re 's/\{\{key\}\}/17f5448de5bba6da56bd013c43d73df6/g' app/etc/local.xml
  - sed -i -re 's/\{\{db_prefix\}\}//g' app/etc/local.xml

  - mysql -e 'create database contactlab_db;'
  - mysql -e 'create database contactlab_test;'
  - php cron.php
script: phpunit tests
